KPIMetricsSystem/KPIMetricsSystem/Controllers/KPIController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KpiMetricsSystem.Models;

namespace AspnetIdentitySample.Controllers
{
    public class kpiController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: /kpi/
        public ActionResult Index()
        {
            return View(db.KPIs.ToList());
        }

        // GET: /kpi/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KPI kpi = db.KPIs.Find(id);
            if (kpi == null)
            {
                return HttpNotFound();
            }
            return View(kpi);
        }

        // GET: /kpi/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /kpi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,KPIName")] KPI kpi)
        {
            if (ModelState.IsValid)
            {
                db.KPIs.Add(kpi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kpi);
        }

        // GET: /kpi/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KPI kpi = db.KPIs.Find(id);
            if (kpi == null)
            {
                return HttpNotFound();
            }
            return View(kpi);
        }

        // POST: /kpi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,KPIName")] KPI kpi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kpi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kpi);
        }

        // GET: /kpi/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KPI kpi = db.KPIs.Find(id);
            if (kpi == null)
            {
                return HttpNotFound();
            }
            return View(kpi);
        }

        // POST: /kpi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            KPI kpi = db.KPIs.Find(id);
            db.KPIs.Remove(kpi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

KPIMetricsSystem/KPIMetricsSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - KPI Metrics System Group2</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            @if(Request.IsAuthenticated)
            {
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("KPI Metrics System", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            }
            else
            { 
                @Html.ActionLink("KPI Metrics System", "Welcome", "Home", null, new { @class = "navbar-brand" })
            }
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("KPI", "index", "kpi")</li>
             
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - KPI Metrics System Group2</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>